def Students():
    students=[
        {
            "name":"Prem",
            "age":25,
            "admno":123,
            "college":"sct"            
        },
        {
            "name":"rahul",
            "age":22,
            "admno":456,
            "college":"cet"            
        },
        {
            "name":"yedu",
            "age":26,
            "admno":888,
            "college":"tkm"            
        },
        {
            "name":"sanjay",
            "age":24,
            "admno":678,
            "college":"baselious"            
        },
        {
            "name":"unni",
            "age":23,
            "admno":4567,
            "college":"iit"            
        }
    ]
    return students